# Generated by Django 5.0.6 on 2024-06-02 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_categories_photo'),
        ('user', '0004_profilemaster_specialization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
        migrations.AddField(
            model_name='service',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_services', to='user.profilemaster', verbose_name='профиль мастера'),
        ),
        migrations.AddField(
            model_name='service',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialist_services', to='user.specialist', verbose_name='специалист'),
        ),
    ]
