# Generated by Django 5.0.6 on 2024-06-02 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profilemaster_date_creation_profilemaster_link_tg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemaster',
            name='specialization',
            field=models.CharField(choices=[('master', 'мастер'), ('studio', 'студия')], default='master', max_length=25, verbose_name='специализация'),
        ),
        migrations.AlterField(
            model_name='profileimages',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_images', to='user.profilemaster', verbose_name='профиль'),
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('job', models.CharField(max_length=50, verbose_name='кфалификация')),
                ('description', models.TextField(verbose_name='описание')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_specialist', to='user.profilemaster', verbose_name='профиль')),
            ],
        ),
        migrations.AddField(
            model_name='profileimages',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secialist_images', to='user.specialist', verbose_name='специалист'),
        ),
    ]
