
export const RoutesConfig = {  
  LANDING: '/',  
  REGISTER: '/register',  
  LOGIN: '/login',  
  PROFILE: (id) => `/profile/${id}`,  
  SPECIALIST: (id, specId) => `/profile/${id}/specialist/${specId}`,  
  CATALOG: '/catalog',  
  FAVORITES: '/favorites',  
  RECORDING: '/recording',  
  BUSINESS: '/business',  
  BUSINESS_PROFILE: '/business/profile',  
  BUSINESS_PROJECTS: '/business/projects',  
  BUSINESS_PROFILE_CREATION: '/business/profile/creation',  
  BUSINESS_PROFILE_EDIT: '/business/profile/edit',  
  BUSINESS_SPECIALISTS: '/business/specialists',  
  BUSINESS_SPECIALIST: (id) => `/business/specialists/${id}`,  
  BUSINESS_SPECIALISTS_CREATE: '/business/specialists/create',  
  BUSINESS_SPECIALIST_EDIT: (id) => `/business/specialists/${id}/edit`,  
  BUSINESS_CATEGORIES: '/business/categories',  
  BUSINESS_SERVICE: '/business/service',  
  BUSINESS_SERVICE_CREATE: '/business/service/create',  
  BUSINESS_SERVICE_EDIT: (id) => `/business/service/${id}/edit`,  
  BUSINESS_WORK_TIME: '/business/work-time',  
  BUSINESS_WORK_TIME_SPEC: (id) => `/business/work-time/${id}`,  
  BUSINESS_WORK_TIME_EDIT: '/business/work-time/edit',  
  BUSINESS_RECORDING: '/business/recording',  
  BUSINESS_RECORDING_SPEC: '/business/recording/:id',  
  ALL_REVIEWS: (id) => `/all-reviews/${id}`,  
};

// business profile creation if profile exist, etc